project_id = "qbksltxsnpkeaijfihug"

[functions.generate-ebook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.cakto-webhook]
verify_jwt = false

[functions.hotmart-webhook]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false
